### ISSUE TITLE
getManualTests generates too many database queries

### ISSUE THREAD

**Issue by norbertlaposa** [laposa/test-portal#106]
There are too many repeated calls of https://github.com/laposa/test-portal/blob/master/app/app/Models/SessionService.php#L52 on session detail page.

<img width="1274" alt="Screenshot 2024-11-01 at 13 18 57" src="https://github.com/user-attachments/assets/5e2e43da-d63b-46b9-b00a-9a28867c3278">

**Comment by maccadesign** [comment]
@norbertlaposa I have opened a PR which should solve this
